-- BRAMU Metrics V1 — RETIRO CONTROLADO (rollback). Se ejecuta A MANO, un nivel por vez, por Central, SOLO en el entorno indicado.
--
-- Ver docs/BRAMUlab/Operacion/Runbook_Operacion_y_Salida.md («BRAMU Metrics — publicación privada y retiro») y
-- docs/BRAMUlab/Implementacion/Post_Lanzamiento/149_…md §12. Probado en PGlite sobre una base tipo Production con datos
-- (supabase/functions/_shared/metrics-promotion-rehearsal.test.mjs): ningún dato de jugadores, partidos, grupos, Nivel ni Ranking cambia.
--
-- Orden recomendado ante un problema:
--    0. Frontend: reasignar `app.bramulab.com` al deployment anterior de Production (Vercel). No toca la base. Es lo PRIMERO y casi siempre alcanza:
--       el frontend viejo no llama a `register_app_presence` ni sirve `/admin/metrics/`.
--    1. NIVEL 1 — apagar el acceso administrativo (reversible, sin tocar esquema).
--    2. NIVEL 2 — retirar funciones y tablas de lectura de métricas (conserva la presencia ya capturada).
--    3. NIVEL 3 — retiro TOTAL de la captura (DESTRUCTIVO: borra los días de actividad). Solo por decisión expresa de Sebastián.
-- La Edge Function `admin-metrics` se retira aparte (Supabase → Edge Functions → eliminar/desactivar); sin ella nadie puede leer métricas aunque el SQL siga.
--
-- NO ejecutar este archivo entero de corrido: ejecutar SOLO el bloque del nivel elegido.

-- =====================================================================================================================
-- NIVEL 1 — Apagar el acceso (reversible: poner revoked_at = null para reactivar)
-- ESPERADO: la Edge responde 403 a todos, incluido el administrador.
-- =====================================================================================================================
--> update public.metrics_admins set revoked_at = now() where revoked_at is null;

-- =====================================================================================================================
-- NIVEL 2 — Retirar el motor de lectura (NO borra player_activity_days ni register_app_presence)
-- Quita: funciones metrics_* / _metrics_* y las tablas metrics_admins / metrics_internal_players (la lista de admins se pierde: reinsertar al reinstalar).
-- =====================================================================================================================
--> do $$
--> declare r record;
--> begin
-->   for r in
-->     select p.oid::regprocedure as sig
-->       from pg_proc p
-->      where p.pronamespace = 'public'::regnamespace
-->        and (p.proname like 'metrics\_%' escape '\' or p.proname like '\_metrics\_%' escape '\')
-->   loop
-->     execute 'drop function ' || r.sig;
-->   end loop;
--> end $$;
--> drop table if exists public.metrics_admins;
--> drop table if exists public.metrics_internal_players;

-- =====================================================================================================================
-- NIVEL 3 — Retiro TOTAL de la captura de presencia (DESTRUCTIVO e irreversible: se pierden los días de actividad)
-- Requiere haber hecho el NIVEL 2. Restaura el informe de acceso/copia (Bloque 9B, sin `activityDays`) y la eliminación de cuenta (G3, sin borrado de actividad) a sus definiciones previas.
-- Antes de ejecutarlo: el frontend con `recordActivity` ya debe estar retirado (paso 0), o cada apertura de app fallará en silencio (sin efecto visible).
-- =====================================================================================================================
--> create or replace function public.admin_export_player_data(p_player_id uuid)
--> returns jsonb
--> language plpgsql
--> security definer
--> stable
--> set search_path = public
--> as $$
--> declare
-->   v jsonb;
--> begin
-->   v := public._admin_export_player_data_raw(p_player_id);
-->   if v is null or coalesce((v ->> 'ok')::boolean, false) is not true then
-->     return v;
-->   end if;
-->   return public._export_redact_third_parties(v, p_player_id);
--> end;
--> $$;
--> revoke all on function public.admin_export_player_data(uuid) from public, anon, authenticated;
--> grant execute on function public.admin_export_player_data(uuid) to service_role;
--> -- (la eliminación de cuenta vuelve a su definición previa a Metrics: ya no borra actividad)
--> create or replace function public.admin_delete_player_account(p_player_id uuid)
--> returns jsonb
--> language plpgsql
--> security definer
--> set search_path = public
--> as $$
--> declare
-->   v_player public.players;
-->   v_captured_auth_user_id uuid;
--> begin
-->   select * into v_player from public.players where player_id = p_player_id for update;
-->
-->   if v_player is null then
-->     return jsonb_build_object('ok', false, 'code', 'player_not_found');
-->   end if;
-->
-->   if v_player.deleted_at is not null then
-->     select (properties->>'authUserId')::uuid into v_captured_auth_user_id
-->       from public.pilot_events
-->       where event_name = 'account_deleted' and player_id = p_player_id
-->       order by created_at desc
-->       limit 1;
-->     return jsonb_build_object(
-->       'ok', true, 'playerId', p_player_id, 'alreadyDeleted', true, 'authUserId', v_captured_auth_user_id
-->     );
-->   end if;
-->
-->   if v_player.type <> 'registered' then
-->     return jsonb_build_object('ok', false, 'code', 'not_a_registered_account');
-->   end if;
-->
-->   v_captured_auth_user_id := v_player.auth_user_id;
-->
-->   -- ---- B2c/P0.3: salir de TODOS los grupos (Issue #4), en esta misma transacción. ----
-->   perform public._groups_account_deletion_cleanup(p_player_id);
-->
-->   update public.players set
-->     display_name = 'Jugador eliminado',
-->     is_active = false,
-->     deleted_at = now(),
-->     auth_user_id = null,
-->     updated_at = now()
-->   where player_id = p_player_id;
-->
-->   update public.profiles set
-->     username = null,
-->     first_name = null,
-->     last_name = null,
-->     display_name = null,
-->     avatar_url = null,
-->     birth_date = null,
-->     gender = null,
-->     dominant_hand = null,
-->     preferred_side = null,
-->     competitive_branch = null,
-->     location_id = null,
-->     location_effective_from = null,
-->     phone = null,
-->     allow_whatsapp_contact = false,
-->     current_category = null,
-->     current_category_at = null,
-->     ranking_opt_in = false,
-->     updated_at = now()
-->   where player_id = p_player_id;
-->
-->   update public.match_participants
-->     set display_name_snapshot = 'Jugador eliminado'
-->     where player_id = p_player_id;
-->
-->   -- V04.29: las identidades provisionales que esta cuenta había recuperado (tombstones) conservan el nombre con el
-->   -- que alguien las cargó: se anonimizan igual que la cuenta. La estructura deportiva (match_participants.player_id ya
-->   -- apunta a la cuenta) y la auditoría de player_identity_recoveries se preservan sin PII adicional.
-->   update public.players
-->     set display_name = 'Jugador eliminado', updated_at = now()
-->     where recovered_into_player_id = p_player_id;
-->
-->   delete from public.intelligence_match_outputs
-->     where match_id in (select match_id from public.match_participants where player_id = p_player_id);
-->
-->   delete from public.match_user_state where player_id = p_player_id;
-->   delete from public.notifications where player_id = p_player_id;
-->
-->   delete from public.player_saved_players
-->     where owner_player_id = p_player_id or saved_player_id = p_player_id;
-->   delete from public.ranking_network_hidden
-->     where player_id = p_player_id or hidden_player_id = p_player_id;
-->
-->   insert into public.pilot_events (event_name, player_id, properties)
-->   values ('account_deleted', p_player_id, jsonb_build_object('authUserId', v_captured_auth_user_id));
-->
-->   return jsonb_build_object(
-->     'ok', true, 'playerId', p_player_id, 'alreadyDeleted', false,
-->     'authUserId', v_captured_auth_user_id
-->   );
--> end;
--> $$;
--> revoke all on function public.admin_delete_player_account(uuid) from public;
--> revoke all on function public.admin_delete_player_account(uuid) from anon;
--> revoke all on function public.admin_delete_player_account(uuid) from authenticated;
--> grant execute on function public.admin_delete_player_account(uuid) to service_role;
--> drop function if exists public.register_app_presence(text, text, text);
--> drop table if exists public.player_activity_days;
